include:
  - project: vkpr/templates
    file: Full-Workflow-GitLab-Backend.gitlab-ci.yml

variables:
  TF_VAR_do_token: $DO_TOKEN
  TF_VAR_cluster_name: $CLUSTER_NAME
  TF_VAR_prefix_version: $K8S_VERSION
  TF_VAR_region: $REGION

init:
  extends: .init
  before_script:
    - echo -e "credentials \"gitlab.com\" {\n  token = \"$CI_JOB_TOKEN\"\n}" > $TF_CLI_CONFIG_FILE
  environment: $CI_COMMIT_BRANCH
  except:
    - master

validate:
  extends: .validate
  environment: $CI_COMMIT_BRANCH

build:
  extends: .build
  environment: $CI_COMMIT_BRANCH

deploy:
  extends: .deploy
  artifacts:
    paths:
      - ./kube
  environment: $CI_COMMIT_BRANCH

destroy:
  extends: .destroy
  environment: $CI_COMMIT_BRANCH
