---

region: "nyc1"
cluster_name: "digitalocean-vkpr-cluster"
prefix_version: 1.21.9

node_pool_default:
  name: digitalocean-vkpr-node-pool
  size: s-2vcpu-2gb
  node_count: 2

additional_node_pools: {}