name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
        continue-on-error: true
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
          key: terraform-lock
      - name: Terraform Init
        id: init
        run: terraform init

  plan:
    runs-on: ubuntu-latest
    needs: init
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
            plan.cache
          key: terraform-lock
      - name: Terraform Plan
        run: terraform plan -lock=false -no-color -out plan.cache
      - uses: actions/cache@v3
        with:
          path: plan.cache
          key: terraform-plan

      #- name: "Upload Artifact"
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: plan-file
      #    path: plan.cache

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: Apply
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - uses: actions/cache@v3
        with:
          path: |
            .terraform/**
            .terraform.lock.hcl
          key: terraform-lock
      - uses: actions/cache@v3
        with:
          path: plan.cache
          key: terraform-plan
      - name: Terraform show
        run: terraform show -json plan.cache

      #- name: Terraform Apply
      #  id: plan
      #  run: terraform plan -lock=false -no-color -out plan.cache

  destroy:
    runs-on: ubuntu-latest
    needs: apply
    environment:
      name: Destroy
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
