name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Cache .terraform
        uses: actions/cache@v3
        with:
          path: |
            .terraform.lock.hcl
            .terraform/**
          key: terraform_lock

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

  plan:
    runs-on: ubuntu-latest
    needs: init
    environment:
      name: Plan
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: Use cache .terraform
        uses: actions/cache@v3
        with:
          path: |
            .terraform.lock.hcl
            .terraform/**
          key: terraform_lock
      - name: Terraform Plan
        run: terraform plan -lock=false -no-color -out plan.cache

      #- name: "Upload Artifact"
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: plan-file
      #    path: plan.cache

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: Apply
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: Terraform show
        run: terraform show -json plan.cache

      #- name: Terraform Apply
      #  id: plan
      #  run: terraform plan -lock=false -no-color -out plan.cache

  destroy:
    runs-on: ubuntu-latest
    needs: apply
    environment:
      name: Destroy
    env:
      TF_VAR_do_token: "${{ secrets.DO_TOKEN }}"
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
